### ISSUE TITLE
Issue while installing elastalert on windows 10

### ISSUE THREAD

**Issue by mehrots** [Yelp/elastalert#2515]
I am getting below issue while installing elastalert on windows 10 using   'pip install elastalert'.
I have python 3.7.4, elastic search 7.3.1 and kibana 7.3.1 installed on my machine.

blist/_blist.c(7742): fatal error C1070: mismatched #if/#endif pair in file 'C:\Users\sachin_mehrotra\AppData\Local\Temp\easy_install-lfh0phy0\blist-1.3.6\blist\_blist.c'
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by mehrots** [comment]
I have tried to install elast alert on two windows 10 machine and i got the same issue on both the machines

**Comment by mehrots** [comment]
It worked with python version 3.6.x.Thanks for the help.
