### ISSUE TITLE
Master branch fails to work with Elasticsearch 7.1.0, but works fine with Elasticsearch 7.0.2 [Compatibility Issue] 

### ISSUE THREAD

**Issue by Shashankft9** [Yelp/elastalert#2599]
Hi, 

I tried to use master branch simply because I wanted to test some recent changes you have made there, but when I ran the setup.py which includes 'elasticsearch>=7.0.0' in install_requires, by default elasticsearch 7.1.0 is installed with elastalert v0.2.1 
And when I run the rule, following output is thrown:
```
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1270, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 868, in run_rule
    self.set_starttime(rule, endtime)
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 711, in set_starttime
    last_run_end = self.get_starttime(rule)
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 690, in get_starttime
    _source_include=['endtime', 'rule_name'])
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-7.1.0-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped
TypeError: search() got an unexpected keyword argument '_source_include'
```

I then changed the dockerfile with version 7.0.2 which I knew works:
```
RUN sed -i 's/elasticsearch>=7.0.0/elasticsearch==7.0.2/' setup.py
```
and it works just fine, perhaps you can share why this is happening and fix this in the new release?
