### ISSUE TITLE
Error when trying to install with 'python setup.py install --user'

### ISSUE THREAD

**Issue by PMDubuc** [Yelp/elastalert#534]
The version of elastalert I was using with elasticsearch 1.7.3 apparently does not work with elasticsearch 2.3.2 (protocol errors)  I'm not sure what version this is.  I've tried doing a local install (since I haven't admin priviledges) from the master with 'python setup.py install --user' and get the following error. We are using Python 2.6.6.

ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-2spc2k/mock-2.0.0/pbr-1.9.1-py2.6.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-2spc2k/mock-2.0.0/pbr-1.9.1-py2.6.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-2spc2k/mock-2.0.0/pbr-1.9.1-py2.6.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-2spc2k/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'

**Comment by PMDubuc** [comment]
Also when I try to run 'pip install -r requirements.txt --user'  I get the following which seems like a separate error:

Collecting configparser==3.3.0r2 (from -r requirements.txt (line 8))
  Could not find a version that satisfies the requirement configparser==3.3.0r2 (from -r requirements.txt (line 8)) (from versions: 3.2.0.post1, 3.2.0.post2, 3.2.0.post3, 3.3.0.post1, 3.3.0.post2, 3.5.0b1, 3.5.0b2)
No matching distribution found for configparser==3.3.0r2 (from -r requirements.txt (line 8))

**Comment by Qmando** [comment]
Not sure about the first problem, sounds like your python or pip installation is not quite right somehow. Google has a few possible suggestions if you search for that error. Maybe try upgrading to 2.7?

As for that specific version of configparser, a newer one would probably work fine. It should exist on pypi though, https://pypi.python.org/pypi/configparser/3.3.0r2

**Comment by PMDubuc** [comment]
I've installed python 2.7.11.  That fixed the first problem.  I also installed the latest version of pip 8.1.2 and that gets me past the second problem but now I get these.  The first exception doesn't seem right because the directory does exist and is empty.  The traceback following the exception may be related to it but seems to be a different problem.  The croniter egg file it's complaining about doesn't exist.


Successfully built PyStaticConfiguration configparser croniter jsonschema mock oauthlib simplejson supervisor tlslite urllib3
Installing collected packages: six, PyStaticConfiguration, argparse, boto, python-dateutil, botocore, configparser, croniter, urllib3, elasticsearch, jsonschema, mock, oauthlib, requests, requests-oauthlib, simplejson, meld3, supervisor, tlslite, unittest2
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: PyStaticConfiguration 0.10.0
    Uninstalling PyStaticConfiguration-0.10.0:
      Successfully uninstalled PyStaticConfiguration-0.10.0
  Found existing installation: argparse 1.4.0
    Uninstalling argparse-1.4.0:
      Successfully uninstalled argparse-1.4.0
  Found existing installation: boto 2.40.0
    Uninstalling boto-2.40.0:
      Successfully uninstalled boto-2.40.0
  Found existing installation: python-dateutil 2.5.3
    Uninstalling python-dateutil-2.5.3:
      Successfully uninstalled python-dateutil-2.5.3
  Found existing installation: botocore 1.4.20
    Uninstalling botocore-1.4.20:
      Successfully uninstalled botocore-1.4.20
  Found existing installation: configparser 3.5.0b2
    Uninstalling configparser-3.5.0b2:
      Successfully uninstalled configparser-3.5.0b2
  Found existing installation: croniter 0.3.12
    Uninstalling croniter-0.3.12:
      Successfully uninstalled croniter-0.3.12
  Found existing installation: urllib3 1.15.1
    Uninstalling urllib3-1.15.1:
      Successfully uninstalled urllib3-1.15.1
  Found existing installation: elasticsearch 2.3.0
    Uninstalling elasticsearch-2.3.0:
      Successfully uninstalled elasticsearch-2.3.0
  Found existing installation: jsonschema 2.5.1
    Uninstalling jsonschema-2.5.1:
      Successfully uninstalled jsonschema-2.5.1
  Found existing installation: mock 2.0.0
    Uninstalling mock-2.0.0:
      Successfully uninstalled mock-2.0.0
  Found existing installation: oauthlib 1.1.1
    Uninstalling oauthlib-1.1.1:
      Successfully uninstalled oauthlib-1.1.1
  Found existing installation: requests 2.10.0
    Uninstalling requests-2.10.0:
      Successfully uninstalled requests-2.10.0
  Found existing installation: requests-oauthlib 0.6.1
    Uninstalling requests-oauthlib-0.6.1:
      Successfully uninstalled requests-oauthlib-0.6.1
  Found existing installation: simplejson 3.8.2
    Uninstalling simplejson-3.8.2:
Exception:
Traceback (most recent call last):
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/dd13/.local/lib/python2.7/site-packages/simplejson-3.8.2-py2.7-linux-x86_64.egg/simplejson'
Traceback (most recent call last):
  File "/projects/pmd23/Python2/CentOS/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/__init__.py", line 221, in main
    return command.main(cmd_args)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1942, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/projects/pmd23/Python2/CentOS/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/home/dd13/.local/lib/python2.7/site-packages/croniter-0.3.12-py2.7.egg'

**Comment by Qmando** [comment]
I highly recommend you use a virtualenv, that way pip doesn't have to downgrade any of your python packages (like simplejson). That being said, I don't know whats causing the errors in pip.

**Comment by PMDubuc** [comment]
I tried again using the pip --prefix option instead of --user and I got past the exception for simplejson but still get the same traceback for the croniter egg file. The /home/dd13/.local/lib/python2.7/site-packages has

drwxr-xr-x  3 dd13 x127   4096 May 18 08:56 croniter
drwxr-xr-x  2 dd13 x127   4096 May 18 08:56 croniter-0.3.8.dist-info

This is different than the 0.3.12 version it's expecting for the egg file.  requirements.txt specifies 0.3.8
I'm sorry, I'm not sure using a virtualenv will work in my case.

**Comment by Qmando** [comment]
I really have no idea what is causing this. You could try installing each package individually. Most of them don't need to be the exact package version in requirements.txt and many are included only for specific features. Can you ignore this error or are you still missing some packages?

**Comment by PMDubuc** [comment]
I changed the croniter version to -.3.12 in requirements.txt and that seems to have worked.
Thanks.  Our admins have version 0.0.70 installed in another place.  will that support ES 2.3.2?

**Comment by Qmando** [comment]
I've fixed a few minor bugs related to ES > 2.0 compatibility within the last several months, but I'm not sure if they were before or after 0.0.70. It should work, but I recommend upgrading regardless.

**Comment by PMDubuc** [comment]
Thanks!
