### ISSUE TITLE
stops working with twilio-6.0.0

### ISSUE THREAD

**Issue by trixter1981** [Yelp/elastalert#980]
Hi there
getting:

`Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 20, in <module>
    from alerts import DebugAlerter
  File "/usr/local/lib/python2.7/dist-packages/elastalert/alerts.py", line 26, in <module>
    from twilio import TwilioRestException
ImportError: cannot import name TwilioRestException
`

Downgraded to twilio==5.6.0 and  works again.
