### ISSUE TITLE
v0.2.0 AttributeError: 'ElastAlerter' object has no attribute 'current_es'

### ISSUE THREAD

**Issue by bangejsans** [Yelp/elastalert#2387]
After upgrading from elastalert v0.2.0b2 to v0.2.0 all of my rules throw the error below. 

`ERROR:root:Uncaught exception running rule Test Rule: 'ElastAlerter' object has no attribute 'current_es'
ERROR:root:Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1259, in handle_rule_execution
num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 900, in run_rule
if not self.run_query(rule, rule['starttime'], endtime):
File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 660, in run_query
self.current_es.clear_scroll(scroll_id=scroll_id)
AttributeError: 'ElastAlerter' object has no attribute 'current_es'
`

I am running on python3.6.8

**Comment by bangejsans** [comment]
When I downgrade back to v0.2.0b2 everything works again.

**Comment by Qmando** [comment]
oops

**Comment by Qmando** [comment]
Fixed and new version pushed
