### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'verbose'

### ISSUE THREAD

**Issue by gokuls** [Yelp/elastalert#2303]
I am facing the issue when i run elastalert-test-rule
what can be issues

i am using 
elasticsearch 7.x

installed elastalert using pip 
elastalert (0.2.0b2)
elasticsearch (7.0.2)

**Comment by Joralmi** [comment]
Hello,
I receive what could be the same error also testing rules but with the dockerized version:

08:21:12.536Z ERROR elastalert-server:
    TestController:  Failed to test rule with error: Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/test_rule.py", line 445, in <module>
        main()
      File "/opt/elastalert/elastalert/test_rule.py", line 441, in main
        test_instance.run_rule_test()
      File "/opt/elastalert/elastalert/test_rule.py", line 408, in run_rule_test
        conf = load_conf(args, defaults, overwrites)
      File "elastalert/config.py", line 47, in load_conf
        configure_logging(args, conf)
      File "elastalert/config.py", line 106, in configure_logging
        if args.verbose and args.debug:
    AttributeError: 'Namespace' object has no attribute 'verbose'

**Installed versions:**
elastalert(0.2.0b2) Built with biosensor docker 
elasticsearch(7.1.1)

**Comment by zffocussss** [comment]
same here

**Comment by Idriel** [comment]
same here 3.0.0-beta.0

**Comment by Qmando** [comment]
Sorry about this. Upon further inspection it looks like this has been broken since https://github.com/Yelp/elastalert/pull/2030, which I clearly didn't test enough. I'll try to get a fix asap

**Comment by mofakhar** [comment]
Hello,

We are facing this same issue with Elasticsearch 7.2. 

 `elastalert-test-rule` gives the error below.

`Traceback (most recent call last):
  File "/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.0b2', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 441, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 408, in run_rule_test
    conf = load_conf(args, defaults, overwrites)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 47, in load_conf
    configure_logging(args, conf)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 106, in configure_logging
    if args.verbose and args.debug:
AttributeError: 'Namespace' object has no attribute 'verbose'
`

**Comment by surendra-github** [comment]
Hi Team,

is this issue fixed ... i am facing the same error with ES 7.3 ????

**Comment by qakart** [comment]
Team me to facing the above issue with ESS 7.3.0 any help highly appreciated

**Comment by ageis** [comment]
I can also reproduce... elastalert 0.2.0b2 (py2)

**Comment by Qmando** [comment]
This wasn't fixed in 0.2.0b2, it was fixed in 0.2.0. You'll need to use that version or newer (0.2.1)
