### ISSUE TITLE
not working after latest commit 

### ISSUE THREAD

**Issue by radhey7705** [Yelp/elastalert#2389]
File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.1.38', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/create_index.py", line 12, in <module>
    from auth import Auth
ImportError: cannot import name 'Auth'

**Comment by Qmando** [comment]
`load_entry_point('elastalert==0.1.38',`

Try running install again (either setup.py install or pip install). The fact that the entrypoint still thinks it's running 0.1.38 indicates an issue. If this IS 0.1.38, you need to use Py2.

**Comment by radhey7705** [comment]
I used the latest version of elastalert 0.2.1 . But that problem is not resolved. So
I am using the previous commit, which is working fine with python2, elastlalert 0.1.39 and elasticalert 7.0.2 library.

**Comment by Qmando** [comment]
This looks like it's happening because you haven't installed all the required libraries. If you've got both python2 and python3 installed, you'll need to use `pip3`.
